### ISSUE TITLE
commit before add

### ISSUE THREAD

**Issue by mwindowshz** [jce-il/git-immersion#12]
Hi
not sure where to post this question.

I am working on git immersion. on Lab 7 STAGING AND COMMITTING
I created the files a.rb and b.rb and then called commit without calling add.

So what hapend?
1. this is the git status now
   [master +2 ~0 -0 !]> git status
   On branch master
   Your branch is ahead of 'origin/master' by 2 commits.
   (use "git push" to publish your local commits)
   Untracked files:
   (use "git add <file>..." to include in what will be committed)
   
   ```
     a.rb
     b.rb
   ```

nothing added to commit but untracked files present (use "git add" to track)
1. how is it possible to commit without adding. and what does this mean?

**Comment by robi-y** [comment]
Hi, better to ask on the forum, here it is for problem or features in the actual exercise.
Anyhow - I think you skipped the "git add" stage, which do appear in lab 7
