### ISSUE TITLE
Problem with "pull request"

### ISSUE THREAD

**Issue by ilanMatityahoo** [jce-il/git-immersion#21]
Hi,

I can't "pull request" in the exercise, I don't know why.
Therefore I send you a log file and hope you can identify the problem.

[ex1_log.txt](https://github.com/jce-il/git-immersion/files/179961/ex1_log.txt)

Thanks,
Ilan

**Comment by robi-y** [comment]
I think you need to go back to your git-immersion repo. make sure you push all commits, and then pull request (you can also start a PR from the github web interface)
