### ISSUE TITLE
should move to better option ?

### ISSUE THREAD

**Issue by praveeno** [jce-il/git-immersion#38]
hello @robi-y,

i recently see code, it all wet code, code is  repeated many times like `Table of Content` is in each file.
we should move to better option like Angular or React, so via liquid templating, we can easily add, update, delete things in files.

let me know what you think about this
thanks

**Comment by robi-y** [comment]
Hello @praveeno 
Thanks for your suggestions
Actually this repo is only a clone of the tutorial by the legendary @jimweirich [RIP](https://github.com/jimweirich/wyriki/commit/d28fac7f18aeacb00d8ad3460a0a5a901617c2d4)
So you better suggest improvements over there http://gitimmersion.com/
